return {
  { "folke/persistence.nvim", enabled = false },
  -- { "epwalsh/obsidian.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  -- { "David-Kunz/gen.nvim", enabled = false },
  -- { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  -- { "folke/flash.nvim", enabled = false },
  -- { "rmagatti/auto-session", enabled = false },
  -- { "nvimdev/lspsaga.nvim", enabled = false },
  -- { "kawre/leetcode.nvim", enabled = false },
  -- { "chrishrb/gx.nvim", enabled = false },
  -- { "echasnovski/mini.surround", enabled = false },
  { "akinsho/flutter-tools.nvim", enabled = false },
  -- { "Wansmer/treesj", enabled = false },
  { "awerebea/git-worktree.nvim", enabled = false },
  { "yetone/avante.nvim", enabled = false },
  -- { "CopilotC-Nvim/CopilotChat.nvim", enabled = false },
}
